- name: run container
  docker_container:
    name: wordpress
    image: "{{ image }}"
    ports: 81:80
    state: started
    
#- name: install pip
 # apt:
  #  name: python3-pip
   # state: present

#- name: pip install docker-py
  #pip:
   # name:
    #  - docker
    "  - docker-compose
    #executable: pip3

#- name: run container
 # docker_container:
  #  name: wartest
   # image: "{{ image }}"
    #ports: 8081:8080
    #state: started
